### ISSUE TITLE
Algorithm Negotiation Failed 

### ISSUE THREAD

**Issue by dhanavellachamy** [wmmihaa/BizTalk-Sftp-Adapter#7]
As one of our vendor is upgrading their SFTP server to have better Data transmission security. Like below 

Ciphers: • aes256-ctr • aes192-ctr • aes128-ctr
MAC algorithms : • hmac-sha256 • hmac-sha2-256 • hmac-sha2-512

We are currently using Biztalk 2013 R2  and I tried connecting using the Eldos adapter it doesnot seems to be connecting the SFTP servers. Below is the errors we are getting 

Method: Blogical.Shared.Adapters.Sftp.SftpReceiverEndpoint.EndpointTask
Error: Uri:SFTP://b.com:22/outgoing/abc.*
 
------------------------------
Information:
Type: System.Exception
Target: 
Message: Uri:SFTP://b.com:22/outgoing/abc.*
Stacktrace:
 

------------------------------
Type: System.Exception
Target: Void connect(Boolean)
Message: Unable to connect to Sftp host[b.com]
Stacktrace:
   at Blogical.Shared.Adapters.Sftp.SharpSsh.Sftp.Dir(String fileMask, String uri, ArrayList filesInProcess, Boolean trace)
   at Blogical.Shared.Adapters.Sftp.SftpReceiverEndpoint.PickupFilesAndSubmit()
   at Blogical.Shared.Adapters.Sftp.SftpReceiverEndpoint.EndpointTask()
 

------------------------------
Type: Tamir.SharpSsh.jsch.JSchException
Target: Void connect(Int32)
Message: Algorithm negotiation fail
Stacktrace:
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.SshBase.ConnectSession(Int32 tcpPort)
   at Tamir.SharpSsh.SshBase.Connect(Int32 tcpPort)
   at Blogical.Shared.Adapters.Sftp.SharpSsh.Sftp.connect(Boolean force

**Comment by narrileo** [comment]
hello All, I am curious to see if there i s any solution for this. Appreciate the response in advance.

**Comment by madilgul** [comment]
I am facing similar issue and have hit a dead end, No solution is available for this issue. or if it is  there i am not able to find it.
Did any one here solve this issue. Please share. Thanks.
